// export const searchData = [
//   {
//     route: "/intro_to_veerge",
//     searchQuery: "Introduction veerge system",
//     topic: "Intro to Veerge",
//   },
//   {
//     route: "/create_online_store",
//     searchQuery: "Create store how to",
//     topic: "How to create an online store",
//   },
//   {
//     route: "/first_time_setup",
//     searchQuery: "Setup veerge how to",
//     topic: "How to set up a veerge account",
//   },
//   {
//     route: "/first_time_setup",
//     searchQuery: "Password setup how to",
//     topic: "How to set up a veerge account",
//   },
//   {
//     route: "/listings/create_listing",
//     searchQuery: "Listings create how to",
//     topic: "How to create listings",
//   },

//   {
//     route: "/listings/create_unit",
//     searchQuery: "Allocation unit create how to",
//     topic: "How to create unit allocations",
//   },
//   {
//     route: "/create_client_account",
//     searchQuery: "Client account signup create how to",
//     topic: "How create client account",
//   },
//   {
//     route: "/listings/archive_unit",
//     searchQuery: "Archive how to",
//     topic: "How to archive unit ",
//   },
//   {
//     route: "/agents_signup",
//     searchQuery: "Agents signup how to",
//     topic: "How to sign up as an agent",
//   },
//   {
//     route: "/listings/fractionalize_asset#frac",
//     searchQuery: "Fraction how to",
//     topic: "How users buy fractions",
//   },
//   {
//     route: "/fractional_real_estate#asset",
//     searchQuery: "asset fraction",
//     topic: "Asset management",
//   },
//   {
//     route: "/fractional_real_estate",
//     searchQuery: "Real estate fraction",
//     topic: "Fractional real estate",
//   },
//   {
//     route: "/inspections",
//     searchQuery: "inspect property",
//     topic: "Inspections on Veerge",
//   },
//   {
//     route: "/change_contact",
//     searchQuery: "contact how",
//     topic: "Change contact person",
//   },
// ];

//prettier-ignore
export const helpSearchData = [
  { pageTitle: 'Overview of Myxellia', page: 'Overview', link: '/overview', title: 'Overview of myxellia', type:'article' },
  { pageTitle: 'Overview of Myxellia', page: 'Overview', link: '/overview#engage', title: 'System of engagement', type:'topic' },
  { pageTitle: 'Overview of Myxellia', page: 'Overview', link: '/overview#trust', title: 'System of trust', type:'topic' },
  { pageTitle: 'Overview of Myxellia', page: 'Overview', link: '/overview#intelligence', title: 'System of intelligence', type:'topic' },
  { pageTitle: 'My Account Has Been Approved-What’s Next?', page: 'Overview', link: '/approved_what_next', title: 'My Account Has Been Approved-What’s Next?', type:'article' },
  { pageTitle: 'My Account Has Been Approved-What’s Next?', page: 'Overview', link: '/approved_what_next#testing', title: 'Testing and pilot phase', type:'topic' },
  { pageTitle: 'My Account Has Been Approved-What’s Next?', page: 'Overview', link: '/approved_what_next#training', title: 'Training & Change Management', type:'topic' },
  { pageTitle: 'My Account Has Been Approved-What’s Next?', page: 'Overview', link: '/approved_what_next#migration', title: 'Business Migration & Setup', type:'topic' },
  { pageTitle: 'Getting Started: A Simple & Quick One', page: 'Overview', link: '/getting_started', title: 'Getting Started: A Simple & Quick One', type:'article' },
  { pageTitle: 'Getting Started: A Simple & Quick One', page: 'Overview', link: '/getting_started#understanding', title: 'Understanding the environment', type:'topic' },
  { pageTitle: 'Getting Started: A Simple & Quick One', page: 'Overview', link: '/getting_started#live', title: 'The live environment(Production Platform)', type:'topic' },
  { pageTitle: 'Getting Started: A Simple & Quick One', page: 'Overview', link: '/getting_started#templates', title: 'Stores and Templates', type:'topic' },
  { pageTitle: 'Getting Started: A Simple & Quick One', page: 'Overview', link: '/getting_started#protected', title: 'How to stay protected', type:'topic' },
  { pageTitle: 'My Manager Told Me About This—Where Do I Start?', page: 'ApplicationGuide', link: '/where_to_start', id: 'the_veerge', title: 'My Manager Told Me About This—Where Do I Start?', type:'article' },
  { pageTitle: 'Myxellia’s Partners Program', page: 'Myxellia’s Partners Program', link: '/partner_program', title: 'Myxellia’s Partners Program', type:'article'  },
  { pageTitle: 'Myxellia’s Partners Program', page: 'Myxellia’s Partners Program', link: '/partner_program#whypartner', title: 'Why partner with Myxellia?', type:'topic'  },
  { pageTitle: 'Myxellia’s Partners Program', page: 'Myxellia’s Partners Program', link: '/partner_program#howitworks', title: 'How it works', type:'topic'  },
  { pageTitle: 'Myxellia’s Partners Program', page: 'Myxellia’s Partners Program', link: '/partner_program#join', title: 'Who should join?', type: 'topic' },
  { pageTitle: 'Myxellia’s Partners Program', page: 'Myxellia’s Partners Program', link: '/partner_program#partnersbenefit', title: 'Partner’s benefits at a glance', type: 'topic' },
  { pageTitle: 'Setting Up Your Account', page: 'Fisrttimesetup', link: '/setting_up', id: 'account', title: 'Setting Up Your Account', type:'article' },
  { pageTitle: 'Setting Up Your Account', page: 'Fisrttimesetup', link: '/setting_up#requirements', id: 'account', title: 'Registration Requirements', type:'topic' },
  { pageTitle: 'Setting Up Your Account', page: 'Fisrttimesetup', link: '/setting_up#guide', id: 'account', title: 'Step-by-step guide to setting up your account' , type:'topic'},
  { pageTitle: 'Setting Up Your Account', page: 'Fisrttimesetup', link: '/setting_up#application', id: 'account', title: 'Application Review', type: 'topic' },
  { pageTitle: 'Setting Up Your Account', page: 'Fisrttimesetup', link: '/listings', id: 'account', title: 'Listings', type:'article' },
  { page: 'Fisrttimesetup', link: '/listings#listing?', id: 'account', title: 'What is a listing?', type:'topic' },
  { page: 'Fisrttimesetup', link: '/listings#typeoflisting', id: 'account', title: 'The two types of listing' , type:'topic'},
  { page: 'Fisrttimesetup', link: '/listings#difference', id: 'account', title: 'Difference between a unit and a listing?', type: 'topic' },
  { page: 'Fisrttimesetup', link: '/listings#paymentplans', id: 'account', title: 'What you need to know about payment plans', type:'topic' },
  { page: 'Fisrttimesetup', link: '/listings#closingcosts', id: 'account', title: 'What you need to know about closing costs', type: 'topic' },
{ page: 'Fisrttimesetup', link: '/listings#allocations', id: 'account', title: 'What you need to know about allocations', type:'topic' },
{ page: 'Fisrttimesetup', link: '/listings#archiving', id: 'account', title: 'When some units aren’t for sale (Archiving Units)', type:'topic' },
  { page: 'Fisrttimesetup', link: '/listings#inspections', id: 'account', title: 'What you need to know about inspections', type: 'topic' },
 {  link: '/how_protected', title: 'How you’re protected', type:'article'  },
  {  link: '/how_protected#safety', title: 'Safety First', type:'topic'  },
  {  link: '/how_protected#commitment', title: 'Commitment to data protection', type:'topic'  },
  {  link: '/how_protected#signups', title: 'Rigorous security measure', type: 'topic' },
  { link: '/how_protected#partnersbenefit', title: 'Encrypted backup and disaster resillience', type: 'topic' },
   {  link: '/setting_up', title: 'Setting Up Your Account', type:'article'  },
  {  link: '/setting_up#requirements', title: 'Registration Requirements', type:'topic'  },
  {  link: '/setting_up#guide', title: 'Step-by-step guide to setting up your account', type:'topic'  },
  {  link: '/setting_up#review', title: 'Application Review', type: 'topic' },
  {  link: '/listing/create_listing', title: 'How to create a Listing', type: 'article' },
  {  link: '/listing/create_listing#usecase', title: 'Creating a multi-family listing or a gated community listing', type: 'topic' },
  {  link: '/listing/create_listing#needtoknow', title: 'What you need to know', type: 'topic' },
  {  link: '/listing/create_listing#guide', title: 'step', type: 'topic' },
  {  link: '/listing/change_listing', title: 'How to change listing information', type: 'article' },
  {  link: '/listing/change_listing#edit', title: 'Edit listing information', type: 'topic' },
  {  link: '/listing/change_listing#modify', title: 'Modifying unit information', type: 'topic' },
  {  link: '/listing/change_listing#payment', title: 'Editing payment plan', type: 'topic' },
  {  link: '/listing/change_listing#unitprice', title: 'How to modify unit price', type: 'topic' },
  {  link: '/listing/change_listing#unitquantity', title: 'How to modify unit quantity', type: 'topic' },
  {  link: '/listing/archive_unit#', title: 'How to archive a unit', type: 'article' },
  {  link: '/listing/archive_unit#remove', title: 'How to remove from archive', type: 'topic' },
  {  link: '/listings/create_allocations', title: 'How to create unit allocations', type: 'article' },
  {  link: '/listings/create_allocations#csv', title: 'Create unit allocations using a CSV file', type: 'topic' },
  {  link: '/listings/create_allocations#manual', title: 'Create unit allocations manually', type: 'topic' },
  {  link: '/setting_up', title: 'Setting Up Your Account', type: 'article' },
  {  link: '/setting_up#requirements', title: 'Registration Requirements', type: 'topic' },
  {  link: '/setting_up#guide', title: 'Step-by-step guide to setting up your account', type: 'topic' },
  {  link: '/setting_up#review', title: 'Application Review', type: 'topic' },
  {  link: '/clients/schedule', title: 'Schedule Inspections', type: 'article' },
  {  link: '/clients/schedule#schedule', title: 'How to Schedule Inspection on behalf of a User', type: 'topic' },
  {  link: '/fractionalise', title: 'How to fractionalise a property', type: 'article' },
  {  link: '/clients/client_account', title: 'Why Client Accounts Matter', type: 'article' },
  { link: '/clients/client_account#owning', title: 'Owning the client relationship from day one', type: 'topic' },
  { link: '/clients/client_account#buyer', title: 'The right way to handle a potential buyer', type: 'topic' },
  { link: '/clients/client_account#thinking', title: 'Thinking beyond immediate sales', type: 'topic' },
  { link: '/clients/client_account#question', title: 'So, what’s the real question?', type: 'topic' },
  { link: '/clients/client_payment#update', title: 'How to update transactions manually', type: 'topic' },
  { link: '/clients/client_payment#after-update', title: 'What happens after updating the transactions?', type: 'topic' },
  { link: '/clients/client_payment#faq', title: 'Frequently Asked Questions (FAQs)', type: 'topic' },
   { link: '/clients/manage_clients', title: 'Managing Other Client Interactions & Property Transfers', type: 'article' },
  { link: '/clients/manage_clients#schedule-inspection', title: 'How to schedule an inspection on behalf of a client', type: 'topic' },
  { link: '/clients/manage_clients#blacklist', title: 'How to blacklist an account', type: 'topic' },
  { link: '/clients/manage_clients#transfer-ownership', title: 'How to transfer ownership of a property', type: 'topic' },
  { link: '/clients/manage_clients#terminate-transaction', title: 'How to terminate a transaction', type: 'topic' },
  { link: '/clients/manage_clients#additional-costs', title: 'How to request additional costs', type: 'topic' },
   { link: '/clients/update_documents', title: 'How to update documents', type: 'article' },
  { link: '/clients/update_documents#update', title: 'Why update documents?', type: 'topic' },
  { link: '/clients/update_documents#steps', title: 'Steps to update documents', type: 'topic' },
]

//prettier-ignore
export const blogSearchData = [
  { pageTitle: 'Fractional Ownership', page: 'Fractional_ownership', link: '/blog/fractional_ownership', id: 'overview', title: 'Overview' },
  { pageTitle: 'Fractional Ownership', page: 'Fractional_ownership', link: '/blog/fractional_ownership', id: 'how_fractional', title: 'How fractional works the Veerge way' },
  { pageTitle: 'Inventory', page: 'Inventory', link: '/blog/inventory', id: 'overview', title: 'Overview' },
  { pageTitle: 'Inventory', page: 'Inventory', link: '/blog/inventory', id: 'benefit', title: 'Benefits of this system' },
  { pageTitle: 'Lead Management', page: 'Lead_management', link: '/blog/lead_management', id: 'overview', title: 'Overview' },
  { pageTitle: 'Lead Management', page: 'Lead_management', link: '/blog/lead_management', id: 'benefit', title: 'Benefits of this system' },
  { pageTitle: 'New Era', page: 'New_era', link: '/blog/new_era', id: 'idea_for', title: 'Idea for innovation' },
  { pageTitle: 'New Era', page: 'New_era', link: '/blog/new_era', id: 'what_is', title: 'What is Veerge?' },
  { pageTitle: 'New Era', page: 'New_era', link: '/blog/new_era', id: 'how_does', title: 'How does Veerge deliver those values effectively' },
  { pageTitle: 'Revenue Recognition', page: 'Revenue_recognition', link: '/blog/revenue_recognition', id: 'overview', title: 'Overview' },
  { pageTitle: 'Revenue Recognition', page: 'Revenue_recognition', link: '/blog/revenue_recognition', id: 'benefit', title: 'Benefits' },
  { pageTitle: 'Transforming Business', page: 'Transforming_business', link: '/blog/transforming_business', id: 'a_ticket', title: 'A ticket system serves as an indispensable tool within the realm' },
  { pageTitle: 'Transforming Business', page: 'Transforming_business', link: '/blog/transforming_business', id: 'perks', title: 'Perks of a Ticketing System' },
  { pageTitle: 'Veerge Data', page: 'Veerge_data', link: '/blog/veerge_data', id: 'overview', title: 'Overview' },
  { pageTitle: 'Veerge Data', page: 'Veerge_data', link: '/blog/veerge_data', id: 'machine_leaning', title: 'Machine Learning, Deep Learning & AI' },
  { pageTitle: 'Veerge Data', page: 'Veerge_data', link: '/blog/veerge_data', id: 'why_veerge', title: 'Why Veerge Matters' },
  { pageTitle: 'Veerge Data', page: 'Veerge_data', link: '/blog/veerge_data', id: 'conclusion', title: 'Conclusion' },
  { pageTitle: 'Why Veerge', page: 'Why_veerge', link: '/blog/why_veerge', id: 'why_veerge', title: 'Why Veerge' },
  { pageTitle: 'Why Veerge', page: 'Why_veerge', link: '/blog/why_veerge', id: 'our_mission', title: 'Our Mission' },
  { pageTitle: 'Why Veerge', page: 'Why_veerge', link: '/blog/why_veerge', id: 'our_value', title: 'Our Value' },
  { pageTitle: 'Why Veerge', page: 'Why_veerge', link: '/blog/why_veerge', id: 'our_culture', title: 'Our Culture' },
]
